# Numpy - exercises
## Creating objects
Create the following objects:
* 10-element, 0-dimensional vector of zeros.
* 8-element, 1-dimensional vector of ones.
* 12-element matrix filled with numbers from 2 to 14.
* just as above, but make sure that the numbers are integers.

In [10]:
import numpy as np
zero_vector = np.zeros(10)
ones_vector = np.ones(8)
numbers = np.random.rand()
numbers = np.random.uniform(low = 2, high = 14, size = (12, ))
numbers_int = np.random.randint(2, 14, size = (12,))

array([ 8.5992788 ,  2.16932491,  7.71127668,  4.55205542,  9.78129239,
       12.55673211,  5.38435896,  7.58688424,  6.14441288,  8.2929167 ,
        5.26861668,  8.63273474])

Create the following objects:
* Matrix of dimensions 4,5 filled with random numbers from distribution U~[0,1)
* Matrix of dimensions 3,6 filled with random numbers from distribution N~(0,1)
* Matrix of dimensions 2,5,6 filled with random numbers from beta distribution (0.5, 0.5)

In [17]:
a = np.random.uniform(size = (4,5))
b = np.random.normal(size = (3, 6))
c = np.random.normal(0.5, 0.5, size = (2, 5 ,6))


Transform the last matrix from the previous cell:
* Change its dimension to (x, 6) in such a way that numpy infers x.
* Split it to two halves vertically.
* Split one of the halves horizotally, so you get two quarters (A and B)
* Transform A to a one- and two-dimensional vector in two ways (in both cases): without copying and with copying.
* Transform A and B to shape (x, 2) and concatenate them vertically and horizontally.

In [ ]:
c = c.reshape(-1, 6)
d, e = np.split(c, 2, axis = 1)

Sort the last matrix in four different ways (by rows/by columns, ascending/descending).

In [30]:
np.sort(a, axis = 0)
np.sort(a, axis = 1)

array([[0.00703328, 0.52066035, 0.80422388, 0.93250392, 0.97501258],
       [0.20522887, 0.59562903, 0.70433371, 0.7713063 , 0.8905789 ],
       [0.04148857, 0.08626363, 0.17458738, 0.35224804, 0.5179012 ],
       [0.03451078, 0.05417223, 0.32727286, 0.35088279, 0.88284331]])

In [31]:
a

array([[0.80422388, 0.93250392, 0.97501258, 0.00703328, 0.52066035],
       [0.20522887, 0.70433371, 0.59562903, 0.8905789 , 0.7713063 ],
       [0.17458738, 0.5179012 , 0.04148857, 0.35224804, 0.08626363],
       [0.05417223, 0.32727286, 0.88284331, 0.35088279, 0.03451078]])

Implement two-dimenstional Rosenbrock function (https://en.wikipedia.org/wiki/Rosenbrock_function) in two ways: using np.apply_along_axis and for loop.
Compare how fast the two implementations are.

In [ ]:
x = random.normal(size=(10000, 2))

